British-Oceanographic-Data-Centre/COAsT

- coast/COAsT.py
an updated to the 2d plot method to make it more useful also added a simple docstring
> mvp for 2d plot method

- README.md
README into newest develop branch.
> New README.md with contributor guidelines

- coast/DOMAIN.py
- coast/NEMO.py
- coast/TRANSECT.py
- example_scripts/awise_script_for_branch104_fix.py
- unit_testing/unit_test.py
- unit_testing/unit_test_contents.txt
Changes to get transect methods working following the merging of DOMAIN and NEMO.
1. Changes in Transect class
- Changes here are primarily to make the code work with the new class structure. Which is a big improvement.
- Also cleared up some of the variable naming to make it consistent
- Now uses depth calculations from the relevant grid for plotting
2. Changes in NEMO closs
a. Moved find_j_i from domain to nemo and edited it to fit with new class structure
b. Moved get_transect_indices from domain to nemo and edited to fit new class structure
c. added depth_0 calculation for all grids, this is done as part of __init__ and is assigned directly to the NEMO.dataset.depth_0 variable before merging and is therefore set as a coordinate variable. This involved removing a few of the previous …
> Branch 104 fixes for transect

- coast/TIDEGAUGE.py
- unit_testing/unit_test.py
Fixed small problem with unit test for TIDEGAUGE.
> Fixed small problem with file_list in TIDEGAUGE

- metadata.py
> Remove references/aliases from metadata YAML output

- .gitignore
- unit_testing/unit_test.py
Implemented logging as a unit_testing standard with output going to a log file.
> Add logging to file to unit testing

- unit_testing/unit_test.py
- unit_testing/unit_test_contents.txt
Minor things to tidy unit testing
> unit testing fixes

- coast/TIDEGAUGE.py
- example_scripts/altimetry_tutorial.py
- example_scripts/tidegauge_tutorial.py
@jpolton @anwiseNOCL  I've added two tutorial scripts to example_scripts:
tidegauge_tutorial.py
altimetry_tutorial.py
They both just show off what the two objects do and how to use them.
I also found a very small bug in TIDEGAUGE.py's plot_on_map_multiple(), which I fixed. Completely up to you if you want to review it or not.
> Tutorial scripts added and small bug fix in TIDEGAUGE

- coast/TIDEGAUGE.py
- requirements.txt
Reduced the version of GSW to 3.3.1
> GSW version updated (reduced)

- coast/INTERNALTIDE.py
- example_scripts/internal_tide_pycnocline_diagnostics.py
I've made some little tweaks to INTERNALTIDE class so that I can use it with TRANSECT.
I've updated the example_script internaltide_pycnocline_diagnostics.py to use the new subclass. I've pushed w-grid objects onto transect_t, so I guess the depths are not quite right, but it is only for visualisation.
NB I've not changed anything that effects the unit testing.
I suggest merging this into your branch first as it keeps the number of merges into develop cleaner.
AC: run example_scripts/internal_tide_pynocline_diagnostics.py
> Fixes to work with TRANSECT class

- coast/TIDEGAUGE.py
- coast/stats_util.py
- unit_testing/unit_test.py
- unit_testing/unit_test_contents.txt
Optima finding code in a clean branch of develop, ready for merging. Methods:
`TIDEGAUGE.find_high_and_low_waters()`
`stats_util.find_maxima()`
Also fixed a small problem with the previous implementation where minima were being output as negative.
Unit test updated
Old pull request closed.
> Clean optima finding added. Unit test updated

- coast/ALTIMETRY.py
- coast/PROFILE.py
- coast/TIDEGAUGE.py
- coast/__init__.py
- coast/general_utils.py
- coast/plot_util.py
- unit_testing/unit_test.py
New basic PROFILE Class: Not much in it right now. Just a defined data format and a handful of routines:
Routine for reading EN4 data
Three plot routines: plot_profile(), plot_map(), plot_ts_diagram
Subsetting by lonlat box
Also some other changes to existing stuff, which adds some new basic routines and fixes a couple of problems I encountered when  trying to write validation scripts with COAsT:
> general_utils:
>>> compare_angles(): Gets the absolute difference between two angles
>>> cart2polar() and polar2cart() : Conversion between coordinate systems (good for harmonics)
>>> subset_indices_lonlat_box(): Another instance of this routine, but for general use. Tidier than the old methods.
>>> nearest_indices_2D(): Changed a couple of lines to fix a bug in landmasking
> plot_util:
>>> …
> PROFILE CLASS added

- coast/CLIMATOLOGY.py
- coast/__init__.py
- unit_testing/unit_test.py
- unit_testing/unit_test_contents.txt
New CLIMATOLOGY Class added. Contains a routine for lazily creating climatological mean and writing to file. 
Will also need routine for calculating climatological variances and a resampling method in future.
@jpolton @anwiseNOCL Unit testing updated and ready for review
> CLIMATOLOGY object and routine added

- coast/CLIMATOLOGY.py
- unit_testing/unit_test.py
Added an argument to the create_climatology() routine to specify whether there are missing values in the dataset. If there are a different computation is used to create the climatology. Expanded the unit testing to check this is working.
> Climatology handling missing values

- .github/workflows/build_package.yml
- .github/workflows/formatting.yml
- .github/workflows/publish_package.yml
- .github/workflows/verify_package.yml
- coast/ALTIMETRY.py
- coast/CDF.py
- coast/COAsT.py
- coast/DISTRIBUTION.py
- coast/NEMO.py
- coast/TIDEGAUGE.py
- coast/general_utils.py
- coast/gridded.py
- pyproject.toml
This version has some collateral changes to Python code, but these appear to be purely related to stripping extraneous spaces from docstrings. Not sure why this wasn't picked up by my local run of Black, but I don't think it's an issue.
I've also added support for Python 3.9 in the other relevant workflows and applied IntelliJ's YAML lint to all of them.
> Add automatic formatting via Black as a GitHub action

- coast/CLIMATOLOGY.py
> Update to docstring

- coast/config/config_parser.py
- coast/config/config_structure.py
- coast/gridded.py
- config/example_gridded.json
- config/example_indexed.json
Fix for coord_var consistency. Moved out of static vairables and into dataset instead.
> restructured coord_var to be consistent between gridded/indexed

- conda_requirements.txt
- requirements.txt
- setup.py
Adds `utide` into the package build.
Separately added to docs (done).
> add utide to package

- coast/contour.py
- unit_testing/unit_test.py
**A:: Contour**
Updated contourF class with some minor changes made since original release. 
1. contour dataset now includes information about the length contour segments.
2. some of the code has been made more robust
3. no change to unit test was required
**B:: Unit test**
I changed a bit of code in unit_testing item 10c to use np.isclose rather than using == . On different machines the evaluation to a float can be slightly different so this was failing for me when it actually looks fine.
> minor update to the ContourF class

- coast/crps_util.py
- coast/eof.py
- coast/general_utils.py
- coast_v1/cdf.py
- config/example_nemo_BGC.json
- example_scripts/SEAsia_DIC_example_plot.py
- unit_testing/unit_test_BGC.py
Extra adds to read BGC:
configuration file: example_nemo_BGC.json in COAsT/config
example for plotting surface DIC: SEAsia_DIC_example_plot.py in COAsT/example_scripts
unit test file: unit_test_BGC.py in COAsT/unit_testing
The new example domain and data necessary for this to work can be found in livljobs here: /scratch/accord/COAST/ADD_TO_EXAMPLES
(These files need to be added to the examples_files directory)
> Read BGC for SEAsia and do some testings

- conda_dev_requirements.txt
- requirements.txt
- setup.py
@anwiseNOCL the package statsmodels should be included in the python environment right?
> add requirements for statsmodels package

- coast/tidegauge.py
- coast/tidegauge_analysis.py
- unit_testing/test_tidegauge_methods.py
Change of names in Tidegauge.py and Tidegauge_analysis.py. id is now called id_dim to avoid conflcits with Pythons own id function.
Unit test updated and works for me.
> ID dimension updated to id_name - unit test works

- docs.Dockerfile
- markdown_doc_builder.py
- requirements_docs.txt
I'm not a huge fan of the solution we're using, but I've cleaned up our usage of it a little.
> Rework and refactor Markdown docs building.

- .github/workflows/unit_test_contents.yml
- setup.py
- unit_testing/generate_unit_test_contents.py
- unit_testing/unit_test_contents.txt
- unit_testing/unit_test_files.py
Add this https://github.com/British-Oceanographic-Data-Centre/COAsT/blob/develop/unit_testing/generate_unit_test_contents.py to GitActions
> generate test contents

- coast/_utils/crps_util.py
- coast/_utils/docsy_tools.py
- coast/data/coast.py
make all doc strings google doc strings for consistency/ quality
> fix doc strings add types

- coast/_utils/mask_maker.py
- coast/diagnostics/contour.py
- coast/diagnostics/internal_tide.py
Just three minor sets of changes.
1. A NOT operator got dropped in mask_maker when getting rid of xr.ufuncs
2. Just to clarify warning message in Contour
3. Add some info to docstring in pea function
AC
You are happy with changes.
> Minor modifications

- .github/ISSSUE_TEMPLATE/newFeature.yml
copy/mod of the GitHub example template - to help start the conversation
> new feature template

- coast/__init__.py
- coast/_utils/experiments_file_handling.py
- coast/data/gridded.py
- coast/diagnostics/annual_hydrographic_climatology.py
- coast/diagnostics/contour.py
- coast/diagnostics/hydrographic_profiles.py
- coast/diagnostics/internal_tide.py
- unit_testing/test_bgc_gridded_initialisation.py
- unit_testing/test_diagnostic_methods.py
- unit_testing/test_gridded_initialisation.py
- unit_testing/test_isobath_contour_methods.py
- unit_testing/test_profile_methods.py
- unit_testing/test_transect_methods.py
- unit_testing/unit_test_contents.txt
I fixed the issue with `if not np.isclose(np.nansum(nemo_t.dataset.depth_0.values), 1705804300.0)`
There appear to be some later unit testing issues, which I am looking at.
> e3 fixes in calc_bathy() and set_timezero_depths()

- example_scripts/notebooks/regridding_with_xesmf_tutorial.ipynb
Add note on install compatibility
> update xesmf compatability note

- CODE_OF_CONDUCT.md
> adding a code of conduct

- coast/diagnostics/gridded_stratification.py
- example_scripts/notebooks/runnable_notebooks/general/eof_tutorial.ipynb
> update file name

- docker-compose.yml
- dockerfile
- environment.yml
- notebooks.dockerfile
> add compose yml, mount data and scripts, reduce docker image, preserve

- example_scripts/notebooks/runnable_notebooks/failed/potential_energy_tutorial.ipynb
@lukegorman This might fix the problem with this failing notebook.
Edits to ipynb made in place
> fix pea ipynb?

- example_scripts/notebooks/runnable_notebooks/failed/tideguage_validation_tutorial.ipynb
> poss fix for tidegauge ipynb

- example_scripts/notebooks/runnable_notebooks/altimetry/altimetry_tutorial.ipynb
> micro edit

- CITATION.cff
- requirements.txt
- setup.py
update version numbering for new release
> version bump 3.1.1 --> 3.1.2

- coast/data/coast.py
close #581.
Minor change to the loading method to "with as" instead of `file = load_file()`. This makes it more error proof and safely closes netcdf files correctly, even if we get an exception or seg fault along the way.
Updated loading method to "with as" instead of `file = load_file()`. This makes it more error proof and safely closes netcdf files correctly, even if we get an exception or seg fault along the way.
Issue URL: #581 
-
-
> Fixed dangling file openings

- environment.yml
Restricted xarray and dask versions from March 2022
Issue URL: #559 
- Unrestricted dask and xarray versions
> dask and xarray >= 2022.3.0

- coast/_utils/mask_maker.py
- unit_testing/test_maskmaker_methods.py
- unit_testing/unit_test_contents.txt
Issue URL: #594 
- Can now create new mask object but inputting polygon vertices.
> Add MaskMaker().make_region()

- coast/data/tidegauge.py
> fix depreciated syntax. cannot define gridded.landmask = None

- coast/__init__.py
- coast/_utils/mask_maker.py
- coast/data/gridded.py
- coast/data/profile.py
- coast/data/tidegauge.py
- coast/diagnostics/circulation.py
- coast/diagnostics/gridded_stratification.py
- coast/diagnostics/profile_analysis.py
- coast/diagnostics/tidegauge_analysis.py
- example_scripts/notebooks/runnable_notebooks/general/mask_maker_tutorial.ipynb
- unit_testing/test_diagnostic_methods.py
- unit_testing/test_gridded_initialisation.py
- unit_testing/test_profile_methods.py
@jasontempestholt These are the fixes I did during the review of your Pull Request.
If you are happy with these, we (you) can update your branch with them. Then I will merge your branch into Develop.
Use "Files Changed" tab (5cm above) to see the differences:
0. updated to the latest version of Develop
1. changed a few names to make them more COAsT
2. abstracted and simplified your subsetting method in Gridded()
3. refactored the velocity_on_t_points so that the differences across indices are not a function of dimension ordering (I'm also hoping it might scale better with xarray backend magic)
> 606 circulation and fluxes in global model data jp

- coast/_utils/crps_util.py
- unit_testing/test_crps_util.py
- unit_testing/unit_test.py
> Allow CRPS to accept nD arrays - flatten first

- README.md
> create changes for the new release

- example_scripts/notebook_tutorials/runnable_notebooks/gridded/transect_tutorial.ipynb
> correct notebook

- .github/workflows/unit_test_contents.yml
- .github/workflows/verify_package.yml
- CITATION.cff
- setup.py
> correct release
